app:
  port: 3000
  log_level: info
  crontime: "*/1 * * * *"

uptimerobot:
  # api_key: fake_api_key
  api_key: u1980027-61ef8b32efc09790527ad1fb
  pattern: "%group/%index/%name"
  statuses: "2-9"

website:
  title: "服务状态"
  copyright: "楠格"
  links:
    - name: 主页
      href: http://about.nange.cn
    - name: 楠格
      href: http://www.nange.cn
    - name: 探针
      href: http://server.nange.cn
    - name: GitHub
      href: http://github.com/xOS
