app:
#   port: 3000
  log_level: ignore
#   crontime: "*/5 * * * *"

uptimerobot:
  # api_key: fake_api_key
  api_key: u1980027-61ef8b32efc09790527ad1fb
  # pattern: "%group/%name"
  statuses: "2-9"

# website:
#   title: "Uptime Robot Status"
#   copyright: "Uptime Robot"
#   links:
#     - name: Home
#       href: https://uptimerobot.com
#     - name: GitHub
#       href: https://github.com/xOS/StatusPage
